#resource/hex types
DESERT = 0
WHEAT = 1
BRICK = 2
WOOD = 3
WOOL = 4
ORE = 5

#development card types
KNIGHT = 1
VICTORY_POINT = 2
ROAD_BUILDING = 3
YEAR_OF_PLENTY = 4
MONOPOLY = 5

#player turn statuses
WAITING_FOR_TURN = 0
PLACING_INITIAL_SETTLEMENT = 1
PLACING_INITIAL_ROAD = 2
READY_TO_ROLL = 3
MOVING_ROBBER = 5
PLAYING_TURN = 6
WAITING_FOR_TRADE_RESPONSE = 6
CONSIDERING_TRADE = 7